### PR TITLE
[ITensors] Update KrylovKit compat upper bound to v0.8

### PR DESCRIPTION
**Pull request by mofeing**
CC @JoeyT1994

### CODE REVIEW

**Comment by mofeing** [comment]
The documentation test failing is not an issue of this PR.

**Comment by JoeyT1994** [comment]
Thanks! Yeah I think that test can be ignored for now

**Comment by mtfishman** [comment]
I wonder why CompatHelper didn't make a PR for this...

**Comment by mofeing** [comment]
@mtfishman Should I close this pr then?

**Comment by mtfishman** [comment]
We can merge this one and then CompatHelper can handle this kind of thing in the future.

**Pull request merged**
